import { StyleSheet } from "react-native";

export default StyleSheet.create({
    main:{ 
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',    
    },
    view:{
        borderWidth:1,
        borderColor:'#FB8019',
        width:'100%',
        paddingHorizontal:3,
        borderRadius:2,
        height:50
    },
    btn:{
        height:33,
        backgroundColor:'#ED1B1A',
        alignItems:'center',justifyContent:'center',
        paddingHorizontal:35,
        borderRadius:2,
    },
    apply:{
        color:'#000000',
        fontSize:13,
        fontFamily:'Montserrat-SemiBold',
        marginRight:7
    },
    off:{
        color:'#000000',
        fontFamily:'Montserrat-SemiBold',
        fontSize:16
    },
    cart:{
        marginTop:15,
        backgroundColor:'#F5F5F5',
        elevation:5,
        borderRadius:5,
        paddingVertical:9,
        paddingHorizontal:8
    },
    welcome:{
        color:'#000000',
        fontSize:12,
        fontFamily:'Monserrat-Medium'
    },
    space:{
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between'
    },
    detail:{
        color:'#000000',
        fontFamily:'Montserrat-Medium',
        fontSize:12,
        borderBottomWidth:1,
        borderStyle:'dashed'
    },
    btn:{
        backgroundColor:'#ED1B1A',
        paddingHorizontal:10,
        borderRadius:2,
        paddingVertical:2
    },
    ly:{
        fontFamily:'Montserrat-SemiBold',
        fontSize:11,
        color:'#FFFFFF',
    },
    save:{
        color:'#000000',
        fontFamily:'Montserrat-Regular',
        fontSize:12
    }
})