import { StyleSheet } from "react-native";

export default StyleSheet.create({
    main:{
        backgroundColor:'#F4F4F4',
        marginTop:15,
        paddingVertical:6,
        paddingHorizontal:4,
        elevation:3,
        marginBottom:2,
        borderRadius:6
    },
    first:{
        fontSize:12,
        color:'#333333',
        fontFamily:'Montserrat-Medium',
        width:'100%'
    },
    change:{
        fontFamily:'Montserrat-Medium',
        fontSize:12,
        color:'#ED1B1A'},
    view:{
        marginTop:15,
        alignItems:'center',
        justifyContent:'center',
        paddingHorizontal:8
    },
    button:{
        backgroundColor:'#ED1B1A',
        paddingHorizontal:24,
        paddingVertical:12,
        borderRadius:5,
        width:'100%',
        alignItems:'center',justifyContent:'center'
    },
    enter:{
        color:'#ffffff',
        fontFamily:'Montserrat-Bold',
        fontSize:16
    }
})