import { StyleSheet } from "react-native";

export default StyleSheet.create({
    container:{
        elevation:4,
        backgroundColor:'#fff',
        shadowColor:'#000',
        borderRadius:6,
        width:'35%',
        flexDirection:'row',
        paddingVertical:5,
        borderWidth:0.4,
        paddingHorizontal:10,
        alignItems:'center'
    },
    search:{
        fontSize:10,
        fontFamily:'Montserrat-Regular',
        color:'#353535',
        marginLeft:10,
        marginBottom:5
    },
    view:{
        flexDirection:'row',
        justifyContent:'space-between',
        borderBottomWidth:.5,
        borderColor:'#dae1ed'
    },
    view1:{
        borderColor:'#0FAF33',
        borderWidth:1,
        height:16,
        width:16,
        alignItems:'center',
        justifyContent:'center',
        borderRadius:4
    },
    border:{
        height:8,
        width:8,backgroundColor:'#0FAF33',
        borderRadius:4
    },
    tag:{
        backgroundColor:'#EF3837',
        paddingVertical:2,
        paddingHorizontal:8,
        borderRadius:3,marginLeft:8
    },
    best:{
        color:'#fff',
        fontFamily:'Montserrat-Medium',
        fontSize:8
    },
    title:{
        fontFamily:"Montserrat-SemiBold",
        fontSize:15,
        color:'#232323',
        marginTop:4
    },
    title1:{
        fontFamily:"Montserrat-SemiBold",
        fontSize:14,
        color:'#000000',
        marginTop:4
    },
    round:{
        // marginLeft:-20,
        marginTop:10,
        flexDirection:'row',
        alignItems:'center',
    },
    round1:{
        marginLeft:-0,
        marginTop:10,
        flexDirection:'row',
        alignItems:'center',
    },
    review:{
        marginLeft:10,
        color:'#232323',
        fontFamily:'Montserrat-Regular',
        fontSize:13
    },
    image:{
        borderWidth:1,
        width:20,
        height:20,
        alignItems:'center',
        justifyContent:'center',
        borderRadius:10,marginTop:5,
        borderColor:'#dae1ed'
    },
    addCont:{
        borderWidth:1,
        borderColor:'#ED1717',
        flexDirection:'row',
        justifyContent:'space-between',
        width:'70%',
        paddingVertical:5,
        borderRadius:5,
        backgroundColor:'#fff',
        alignItems:'center',
        paddingHorizontal:4
    },
    add:{
        fontFamily:'Montserrat-SemiBold',
        fontSize:12,
        color:'#ED1717',
        marginLeft:25
    },
    plus:{
        fontFamily:'Montserrat-SemiBold',
        fontSize:15,
        color:'#ED1717',
        marginTop:-6,
        marginRight:4
    },
    button:{
        width:'48%',
        height:36,
        alignItems:'center',
        justifyContent:'space-between',
        flexDirection:'row',
        paddingHorizontal:10
    },
    border1:{
        borderWidth:1,
        borderColor:'#FF4141',
        height:16,width:16,
        backgroundColor:'#fff',
        borderRadius:8,
        alignItems:'center',
        justifyContent:'center'
    },
    red:{
        width:8,
        height:8,
        backgroundColor:'#FF0303',
        borderRadius:4
    },
    pref:{
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        // marginTop:10
    },
    border2:{
        borderWidth:1,
        borderColor:'#FF7E07',
        paddingHorizontal:17,
        paddingVertical:1,
        borderRadius:6
    },
    bottom:{ 
        borderWidth:1,
        borderColor:'#000',
        width:'48%',
        padding:2,
        borderRadius:10,
    },
    row:{
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
    },
    text:{
        fontSize:12,
        fontFamily:'Montserrat-Reegular',
        color:'#000',
        margin:5,
        marginTop:-3
    },
    gram:{
        fontFamily:'Montserrat-Medium',
        color:'#000',
        margin:5
    },
    bottom1:{
        alignItems:'center',
        justifyContent:'center',
        bottom:60,
        position:'absolute',
        left:0,right:0
    },
    menu:{
        backgroundColor:'#232323',
        paddingHorizontal:6,
        flexDirection:'row',
        paddingVertical:10,
        borderRadius:3
    },
    home:{
        color:'#6A6A6A',
        fontFamily:'Montserrat-Medium',
        fontSize:13
    },
    cmn:{
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center'
    },
    pl:{
        width:15,
        height:15,
        tintColor:'#6A6A6A'
    },
    header:{
        height:40,
        backgroundColor:'#232323',
        marginTop:-20,
        // marginLeft:-20,
        // marginRight:-20,
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between',
        paddingHorizontal:10
    },
    item:{
        color:'#6A6A6A',
        fontFamily:'Montserrat-Regular',
        fontSize:12
    },
    round2:{
        backgroundColor:'#D9D9D9',
        marginLeft:10,
        paddingHorizontal:5,
        borderRadius:10,
        alignItems:'center',
        justifyContent:'flex-end',
        paddingVertical:2
    },
    num:{
        color:'#000000',
        fontFamily:'Montserrat-Regular',
        fontSize:10
    },
    margin:{
        flexDirection:'row',
        alignItems:'center',
        marginTop:3
    },
    

})